const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const meta={iu:['Fazer Agora','Importante + Urgente'],in:['Planejar','Importante + Não urgente'],nu:['Delegar','Não importante + Urgente'],nn:['Eliminar / Adiar','Baixo impacto']};
let selectedId='t1', focusInterval=null;
const seed=[
{id:'t1',title:'Enviar relatório de expedição',desc:'Preparar e enviar relatório diário das NFs expedidas.',deadline:'today',impact:'Alto',urgency:'Alta',effort:'Médio',duration:45,canDelegate:false,tags:['NF','expedição','relatório'],done:false},
{id:'t2',title:'Responder e-mail do financeiro',desc:'Retornar dados solicitados pelo financeiro.',deadline:'today',impact:'Médio',urgency:'Alta',effort:'Baixo',duration:10,canDelegate:false,tags:['e-mail','financeiro'],done:false},
{id:'t3',title:'Atualizar status das NFs no sistema',desc:'Atualizar andamento operacional.',deadline:'today',impact:'Baixo',urgency:'Alta',effort:'Baixo',duration:15,canDelegate:true,tags:['NF','sistema'],done:false},
{id:'t4',title:'Criar dashboard de KPIs logísticos',desc:'Criar visão de produtividade e pendências.',deadline:'week',impact:'Alto',urgency:'Baixa',effort:'Alto',duration:120,canDelegate:false,tags:['dashboard','KPI'],done:false},
{id:'t5',title:'Reorganizar layout da planilha',desc:'Melhoria visual simples na planilha.',deadline:'none',impact:'Baixo',urgency:'Baixa',effort:'Médio',duration:60,canDelegate:false,tags:['planilha'],done:false}
];
let tasks=JSON.parse(localStorage.getItem('eisenflowTasks')||'null')||seed;
function save(){localStorage.setItem('eisenflowTasks',JSON.stringify(tasks))}
function score(t){let s=0;s+=t.impact==='Alto'?30:t.impact==='Médio'?18:8;s+=t.urgency==='Alta'?25:t.urgency==='Média'?14:5;s+=t.deadline==='today'?20:t.deadline==='tomorrow'?14:t.deadline==='week'?8:2;s+=t.effort==='Baixo'?10:t.effort==='Médio'?6:2;s+=t.canDelegate?-5:5;return Math.max(1,Math.min(100,s))}
function quadrant(t){if(t.canDelegate&&t.impact!=='Alto'&&t.urgency!=='Baixa')return'nu';if(t.impact==='Alto'&&['Alta','Média'].includes(t.urgency)&&['today','tomorrow'].includes(t.deadline))return'iu';if(t.impact==='Alto'||(t.impact==='Médio'&&t.urgency==='Baixa'))return'in';if(t.urgency==='Alta')return'nu';return'nn'}
function color(sc){return sc>=80?'var(--amber)':sc>=55?'var(--teal)':sc>=35?'var(--blue)':'var(--muted2)'}
function enriched(){return tasks.map(t=>({...t,score:score(t),q:quadrant(t)})).sort((a,b)=>b.score-a.score)}
function render(){const data=enriched();['iu','in','nu','nn'].forEach(q=>$('#q-'+q).innerHTML='');data.forEach(t=>$('#q-'+t.q).appendChild(card(t)));$('#taskCount').textContent=data.filter(t=>!t.done).length;renderSidebar(data);renderDetails(data.find(t=>t.id===selectedId)||data[0]);renderDay(data);save()}
function card(t){const div=document.createElement('div');div.className='task-card '+(selectedId===t.id?'selected ':'')+(t.done?'done':'');div.onclick=()=>{selectedId=t.id;render()};div.innerHTML=`<div class="task-top"><div class="task-title">${t.done?'✓ ':''}${t.title}</div><div class="score" style="color:${color(t.score)}">${t.score}</div></div><div class="tags"><span class="tag amber">${t.urgency}</span><span class="tag teal">${t.impact}</span>${t.canDelegate?'<span class="tag blue">delegável</span>':''}<span class="tag">${t.duration}min</span></div>`;return div}
function renderSidebar(data){const mission=data.find(t=>!t.done)||data[0];$('#missionCard').innerHTML=mission?`<div class="section-title amber">Em foco agora</div><b>${mission.title}</b><p class="muted">Score ${mission.score} · ${meta[mission.q][0]}</p>`:'Sem tarefas';$('#missionCard').onclick=()=>{if(mission){selectedId=mission.id;render()}};$('#quickWins').innerHTML=data.filter(t=>!t.done&&t.duration<=30).slice(0,3).map(t=>`<div class="side-item" data-id="${t.id}"><span>${t.title}</span><b>${t.duration}min</b></div>`).join('')||'<p class="muted">Sem ganhos rápidos.</p>';$('#delegateList').innerHTML=data.filter(t=>!t.done&&t.canDelegate).slice(0,3).map(t=>`<div class="side-item" data-id="${t.id}"><span>${t.title}</span><b>→</b></div>`).join('')||'<p class="muted">Nada para delegar.</p>';$$('.side-item').forEach(el=>el.onclick=()=>{selectedId=el.dataset.id;render()})}
function renderDetails(t){if(!t){$('#detailsBody').innerHTML='Sem atividades.';return}selectedId=t.id;const why=t.q==='iu'?'Prazo próximo, impacto relevante e exige ação imediata.':t.q==='in'?'É importante, mas pode ser planejada com calma.':t.q==='nu'?'Tem urgência, mas pode ser repassada para outra pessoa.':'Baixo impacto no resultado de hoje.';$('#detailsBody').innerHTML=`<div class="detail-score"><div class="big-score" style="color:${color(t.score)}">${t.score}</div><div><b>${meta[t.q][0]}</b><p class="muted">${meta[t.q][1]} · ${t.duration}min</p></div></div><div class="info-box"><b>${t.title}</b><p class="muted">${t.desc||'Sem descrição.'}</p></div><div class="row"><span>Urgência</span><b>${t.urgency}</b></div><div class="row"><span>Impacto</span><b>${t.impact}</b></div><div class="row"><span>Esforço</span><b>${t.effort}</b></div><div class="row"><span>Delegável</span><b>${t.canDelegate?'Sim':'Não'}</b></div><div class="info-box"><b>Por que essa prioridade?</b><p class="muted">${why}</p></div><div class="info-box"><b>Próximo passo</b><p class="muted">Comece pela menor ação possível para destravar essa atividade.</p></div><div class="tags">${t.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="actions"><button class="primary-btn" onclick="startFocus('${t.id}')">Modo foco</button><button class="ghost-btn" onclick="toggleDone('${t.id}')">${t.done?'Reabrir':'Concluir'}</button><button class="ghost-btn danger" onclick="deleteTask('${t.id}')">Excluir</button></div>`}
function renderDay(data){$('#dayPlan').innerHTML=data.filter(t=>!t.done).slice(0,8).map((t,i)=>`<div class="time-block" style="border-left-color:${color(t.score)}"><b>${i+1}. ${t.title}</b><br><small>${meta[t.q][0]} · Score ${t.score} · ${t.duration}min</small></div>`).join('')||'<p class="muted">Nenhuma atividade pendente.</p>'}
function toggleDone(id){tasks=tasks.map(t=>t.id===id?{...t,done:!t.done}:t);render()}function deleteTask(id){if(confirm('Excluir esta atividade?')){tasks=tasks.filter(t=>t.id!==id);selectedId=tasks[0]?.id;render()}}function resetForm(){$('#taskForm').reset();$('#duration').value='30';$('#impact').value='Médio';$('#urgency').value='Média';$('#effort').value='Médio'}
$('#newTaskBtn').onclick=()=>{$('#taskModal').classList.remove('hidden');$('#title').focus()};$('#closeModalBtn').onclick=()=>$('#taskModal').classList.add('hidden');$('#taskModal').onclick=e=>{if(e.target.id==='taskModal')$('#taskModal').classList.add('hidden')};
$('#taskForm').onsubmit=e=>{e.preventDefault();const title=$('#title').value.trim();if(!title)return;const tags=$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean);const task={id:'t'+Date.now(),title,desc:$('#description').value.trim(),deadline:$('#deadline').value,impact:$('#impact').value,urgency:$('#urgency').value,effort:$('#effort').value,duration:Number($('#duration').value),canDelegate:$('#canDelegate').value==='true',tags:tags.length?tags:['atividade'],done:false};tasks.unshift(task);selectedId=task.id;save();resetForm();$('#taskModal').classList.add('hidden');render()};
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+btn.dataset.view+'View').classList.add('active')});
$('#clearDoneBtn').onclick=()=>{tasks=tasks.filter(t=>!t.done);selectedId=tasks[0]?.id;render()};
function startFocus(id){const t=enriched().find(x=>x.id===id);if(!t)return;let secs=t.duration*60;$('#focusTitle').textContent=t.title;$('#focusStep').textContent='→ Comece agora e mantenha foco até finalizar o bloco.';$('#focusOverlay').classList.remove('hidden');tick(secs);clearInterval(focusInterval);focusInterval=setInterval(()=>{secs--;tick(secs);if(secs<=0)clearInterval(focusInterval)},1000)}function tick(secs){const m=String(Math.floor(secs/60)).padStart(2,'0');const s=String(Math.max(0,secs%60)).padStart(2,'0');$('#focusTimer').textContent=`${m}:${s}`}$('#exitFocusBtn').onclick=()=>{clearInterval(focusInterval);$('#focusOverlay').classList.add('hidden')};
render();
